logo_url: https://www.triceratops.show/images/logo-400px.png
display_url: https://www.triceratops.show
media_folder: static/episodios
public_folder: /episodios
locale: 'pt'

collections:
  - name: 'episodios'
    label: 'Episódios'
    label_singular: 'Episódio'
    summary: '#{{episode}} {{title}}'
    folder: 'content/episodios'
    create: true
    slug: '{{episode}}'
    delete: false
    sortable_fields: ['publishDate']
      #    editor:
      #      preview: false
    fields:
      - { label: 'Episódio (número)', name: 'episode', widget: 'number', required: false }
      - { label: 'Título', name: 'title', widget: 'string', required: false }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Descrição', name: 'description', widget: 'string', required: false }
      - { label: 'Data de publicação', name: 'publishDate', widget: 'datetime', required: false }
      - { label: 'Arquivo', name: 'podcast_file', widget: 'string', required: false }
      - { label: 'Duração', name: 'podcast_duration', widget: 'string', required: false }
      - { label: 'Tamanho (em bytes)', name: 'podcast_bytes', widget: 'string', required: false }
      - { label: 'Publicado', name: 'published', widget: 'boolean', default: false }
      - { label: 'Youtube', name: 'youtube', widget: 'string', required: false }
      - label: 'Corpo'
        name: 'body'
        widget: 'markdown'
        required: false
        default: |
          ## tocamos
          * {banda} - {música}

          ## mencionados
          * {algum filme mencionado}

          ## escusas
          * {alguma merda que falamos}

          ## otras cositas más
          * [nossa playlist no spotify](https://open.spotify.com/playlist/0UiztKuga6LmTAxWTsUQdw?si=fb96026bc1994d90)
          * nosso email de contato é `contato@triceratops.show`
          * [instagram](https://www.instagram.com/triceratops.show/)
          * [twitter](https://twitter.com/TriceratopsShow/)

