display_url: https://www.triceratops.show
logo_url: https://www.triceratops.show/img/logo-400px.png

public_folder: /episodios
media_folder: static/episodios

locale: 'pt'

collections:
  - name: 'episodios'
    label: 'Episódios'
    label_singular: 'Episódio'
    summary: '#{{episode}} {{title}}'
    folder: 'content/episodios'
    slug: '{{episode}}'
    create: true
    delete: false
    sortable_fields: ['episode', 'publishDate']
    fields:
      - { label: 'Episódio', hint: 'número do episódio', name: 'episode', widget: 'number', required: false }
      - { label: 'Título', name: 'title', widget: 'string', required: false }
      - { label: 'Capa', name: 'image', widget: 'image', required: false }
      - { label: 'Descrição', name: 'description', widget: 'text', required: false }
      - { label: 'Artistas tocados', hint: 'separados por vírgula', name: 'artistas', widget: 'list', required: false }
      - { label: 'Arquivo', name: 'podcast_file', widget: 'string', required: false }
      - { label: 'Duração', hint: 'no formato hh:mm:ss', name: 'podcast_duration', widget: 'string', required: false }
      - { label: 'Tamanho', hint: 'em bytes', name: 'podcast_bytes', widget: 'string', required: false }
      - { label: 'YouTube', name: 'youtube', widget: 'string', required: false }
      - { label: 'Publicado', name: 'published', widget: 'boolean', default: false }
      - { label: 'Data de publicação', name: 'publishDate', widget: 'datetime', required: false }
      - label: 'Corpo'
        name: 'body'
        widget: 'markdown'
        required: false
        default: |
          ## tocamos
          * {banda} - {música}

          ## participaram
          * {alguém que mandou um alô}

          ## recomendamos
          * {algum filme} (*tradução*) (ano), filme massa de fulano

          ## mencionados
          * {algum namedropping}

          ## escusas
          * {alguma merda que falamos}

          ## otras cositas más
          * [nossa playlist no spotify](https://open.spotify.com/playlist/0UiztKuga6LmTAxWTsUQdw?si=fb96026bc1994d90)
          * [instagram](https://www.instagram.com/triceratops.show/)
          * [twitter](https://twitter.com/TriceratopsShow/)
          * nosso email de contato é `contato@triceratops.show`
