on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.92.1'
          extended: true
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Node dependencies
        run: npm ci
      - name: Build site
        run: hugo --minify
        env:
          HUGO_PARAMS_GITSHA: ${{ github.sha }}
      - name: Run checks
        run: npm run check
      - name: Deploy site
        if: github.ref == 'refs/heads/main'
        # https://stackoverflow.com/questions/59511859/how-to-skip-deleting-some-files-when-doing-hugo-deploy
        run: hugo deploy --maxDeletes 0
        env:
          AWS_REGION: 'sa-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
